### ISSUE TITLE
Stroker order has wrong color and text shadow

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#122]
I think maybe it's just the first unexpanded info section, but I noticed "Stroke Order" was ugly today:

<img width="1289" alt="Screenshot 2023-03-31 at 9 39 11 AM" src="https://user-images.githubusercontent.com/653208/229180022-10a6b442-3a08-427b-b5b1-d3559f19c214.png">

I think we need to add something like:

```css
.item-info-injector-accordion > button {
    color: var(--ED-text);
    text-shadow: none;
}
```
