### ISSUE TITLE
Add radical background color to radicals in Radical Combinations panel

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#137]
See https://github.com/Sepitus-exe/WKElementaryDark/issues/119#issuecomment-1497805364

**Comment by wrex** [comment]
Aha.

I found out why WK had an explicit width and height on these. Apparently they sometimes use an image rather than a unicode character for the radical. Without an explicit width and height it blows up to the size of the image (guess which one of the three is an image):


<img width="1245" alt="Screenshot 2023-04-05 at 11 45 06 AM" src="https://user-images.githubusercontent.com/653208/230175723-2a85a59d-9b07-4fa0-9ba5-02e6350fd900.png">

This needs a new rule:

```css
#additional-content ul li span img {
  width: 2rem;
  height: 2rem;
  padding: 0;
}
```
