### ISSUE TITLE
Fix input element with self-study script

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#18]
When the self-study quiz input bar has white text on a white background:

<img width="601" alt="Screenshot 2023-01-14 at 1 13 11 PM" src="https://user-images.githubusercontent.com/653208/212497260-75149b82-255c-46d2-a393-f8540eab65e2.png">

(the entered text is selected so you can see it, otherwise it's invisible).

For reference, here is how it appears with Breeze Dark:

<img width="602" alt="Screenshot 2023-01-14 at 1 17 00 PM" src="https://user-images.githubusercontent.com/653208/212497347-2b8c1585-3db8-4beb-a8ba-0a2f77154def.png">

Aside: I wish that WK had a CSS style guide for user scripts. Would make theming a whole lot easier!

**Comment by Sepitus-exe** [comment]
Looks like the bulk of the issue is the usage of generic selectors e.g. `a`, `span`, `input[type=''text"]`. Making the selectors more strict would somewhat solve the issue, but not provide any inherent formatting for the script. If possible I would like to find a solution that would at least provide color matching for radicals, kanji and vocab.

---

For now, I have pushed out a temporary fix for this specific plugin, but further work should be done on this.

![image](https://user-images.githubusercontent.com/82216846/212524801-77066125-8cc7-49e9-82fc-9f0d61eb6518.png)

**Comment by wrex** [comment]
I'll take a look, but I've not yet looked at actually fixing any other userscripts yet (I just opened the issue so it will be tracked). 

I'm still trying to understand all the existing rules for the default pages, and attempting to simplify some things if at all possible. 

I am making headway (I've mostly finished the dashboard and the review/lessons summary pages already). I've cleaned up a few things and it should be easier to know what will change if you fiddle with any of the custom properties.

One example, I've created the following:

```css
:root {
/* A bunch of custom props for palette colors */

/* Semantic properties */
--ED-text-darkbg: var(--ED-gray-14); /* Light text on a dark background */
--ED-text-lightbg: var(--ED-gray-1); /* Dark text on a light background */

--ED-text-color: var(--ED-text-darkbg); /* Default is light text on a dark background */
```

This way everything just uses `color: --ED-text-color;` everywhere. The parent element of anything that sets a light background, though, should redefine `--ED-text-color`.

For example, the `kotoba-table-list` now renders like this:

<img width="987" alt="Screenshot 2023-01-14 at 10 18 27 PM" src="https://user-images.githubusercontent.com/653208/212526040-c71dbab6-70d2-48d0-8bd7-31b22e30fc54.png">

The CSS looks like this:

```css
 :root {
    --ED-gray-1: #151515; /* darkest */
    /* ... */
    --ED-gray-14: #ffffff;
    --ED-red-1: #9d4745;
    --ED-blue-1: #56638a;
    --ED-green-1: #58b09c;
    --ED-yellow-1: #d7af70;

    /*  Text colors */
    --ED-text-darkbg: var(--ED-gray-14); /* light text against dark bg */
    --ED-text-lightbg: var(--ED-gray-1); /* dark text against light bg */
    
    --ED-text-color: var(--ED-text-darkbg); /* Default is light text / dark bg */
    
    --ED-highlight-text: var(--ED-yellow-1);
    --ED-grayed-text: var(--ED-gray-8); /* de-emphasized text */

    /* Branding colors */
    --ED-brand: var(--ED-red-1);
    --ED-brand-2: var(--ED-yellow-1);

    /* Answer indicators */
    --ED-correct: var(--ED-green-1);
    --ED-incorrect: var(--ED-red-1);

    /* Surfaces / overlapping containers */
    --ED-surface-1: var(--ED-gray-1); /* farthest back */
    --ED-surface-2: var(--ED-gray-3);
    --ED-surface-3: var(--ED-gray-5);
    --ED-surface-4: var(--ED-gray-7);
    --ED-surface-5: var(--ED-gray-9); /* closest to user */

    /* Semantic indication of review vs. lesson */
    --ED-lesson-clr: var(--ED-red-1);
    --ED-review-clr: var(--ED-blue-1);

    /* Semantic indication of item types */
    --ED-radical-clr: var(--ED-red-1);
    --ED-kanji-clr: var(--ED-blue-1);
    --ED-vocab-clr: var(--ED-green-1);
    --ED-extra-clr: var(--ED-yellow-1);

    /* TODo: Box shadows */
}

/* ... */

/* RRW dark text better contrast here */
  .kotoba-table-list table {
    --ED-text-color: var(--ED-text-lightbg);
  }
  
  .kotoba-table-list table a span,
  .kotoba-table-list table a time,
  .kotoba-table-list table td span.pull-right {
    color: var(--ED-text-color);
  }

  .kotoba-table-list tr[class|="radical"],
  .kotoba-table-list tr[class|="kanji"],
  .kotoba-table-list tr[class|="vocabulary"] {
    background-image: none;
  }

  .kotoba-table-list tr[class|="radical"]:nth-child(odd),
  .kotoba-table-list tr[class|="kanji"]:nth-child(odd),
  .kotoba-table-list tr[class|="vocabulary"]:nth-child(odd) {
    filter: brightness(1.1);
  }

  .kotoba-table-list tr[class|="radical"] {
    background-color: var(--ED-radical-clr);
  }

  .kotoba-table-list tr[class|="kanji"] {
    background-color: var(--ED-kanji-clr);
  }

  .kotoba-table-list tr[class|="vocabulary"] {
    background-color: var(--ED-vocab-clr);
  }

/* ... */

```

This way you can theme any colors you want quite easily, just by editing the top rule.

Hopefully this makes sense. If all this is too much to take in as PRs, just let me know. I'm willing to create and maintain my own fork if you'd prefer.

I've been thinking that it might be wiser to take any theming of userscripts _out_ of the base theme. Once the custom properties are stable for the top level theme, people can create their own user-styles for each plugin and just use the same custom props (which will inherit from from the parent). In other words: just one stylesheet for Extreme Dark itself, then another for ED-Ultimate-Timeline, another for ED-Self-Study, etc.

Since the user will install all of these locally, it won't be any slower to load. And managing the CSS rules for each userscript independently would be a whole lot more tractable than one monolithic script. ED itself is just responsible for setting the overall theme custom-props, and overriding the default WK selectors. Each script author (or whoever) can write their own CSS overrides for the theme.

I'm not decided on this yet, but I think it might make sense.
