### ISSUE TITLE
Dash L/R button spans not adapting to --0 class

### ISSUE THREAD

**Issue by Sepitus-exe** [Sepitus-exe/WKElementaryDark#37]
Should be easily fixable by adding a `.lessons-and-reviews__reviews-button--0 span` selector that redefines text color
![image](https://user-images.githubusercontent.com/82216846/213065046-a3eaf41a-b8a3-42cc-89c2-6bf6faa98ab3.png)

**Comment by wrex** [comment]
Uh...

I already implemented this. Isn't it already in main?

**Comment by wrex** [comment]
Yup. Already implemented. Note that I had to up the specificity to get these to apply.

Here are the rules already in main:

```css
.lessons-and-reviews .lessons-and-reviews__lessons-button--0 {
  /* No lessons, no color */
  background-color: var(--ED-surface-4);
}
```

```css
.lessons-and-reviews__lessons-button span {
  background-color: var(--ED-text-color); /* inverse text */
  color: var(--ED-lesson-clr);
}

```
