### ISSUE TITLE
still need to nuke brand-alt

### ISSUE THREAD

**Issue by wrex** [Sepitus-exe/WKElementaryDark#93]
I mentioned doing this, but apparently forgot to ever actually take care of it.

It's only used in this rule:

```css
.subject-legend__item-badge--recently-unlocked,
.component-character__badge,
.character-item__badge {
  background-color: var(--ED-brand-alt);
}
```

I think it's okay to change this to `--ED-brand`.
